version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./node-app:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
